### ISSUE TITLE
ID based on sys.maxsize causes problems with 32-bit systems

### ISSUE THREAD

**Issue by ramonbroox** [armills/jsonrpc-base#7]
As if not using uuid wasn't enough pain, some 32-bit systems cannot hold the random 64 bit ids and return responses as floating point (which isn't strictly incorrect as the JSON RFC makes no claims about it).

e.g. request:
```json
{"jsonrpc": "2.0", "method": "startReading", "params": {}, "id": 1425637920391538181}
```

response:

```json
{"jsonrpc": "2.0", "error": {"code": -1, "message": "Reader already reading"},
    "method": "startReading", "id": 1.4256379203915382e+18}
```

**Comment by emlove** [comment]
I think I'm going to just switch these IDs to using UUIDs. The original logic to use this integer ID comes from [the initial commit of jsonrpc-requests](https://github.com/emlove/jsonrpc-base/commit/5f87bbeaca5a161dd18eb0411db7650301af161e#diff-648446bb8f7cd3507a1794a8014ccc396352d2d56968b0a9099359ac96514844R69-R70), and I can't find any evidence that this comment is true. In fact, as this issue shows a string ID is a lot more likely to be compatible, and I see [other json-rpc libraries that are suggesting using UUIDs as well](https://www.npmjs.com/package/jsonrpc-serializer). In any case, a string UUID for the request ID conforms with both JSON-RPC V1 and V2, so if there's some server that can't handle a string ID the patch belongs there.

**Comment by emlove** [comment]
OK, I've released new versions of `jsonrpc-base`, `jsonrpc-async`, and `jsonrpc-websocket` that now use uuid4 as the request ID.
