### ISSUE TITLE
Automatically omit "params" when it's empty

### ISSUE THREAD

**Issue by Makman2** [armills/jsonrpc-base#8]
Hello :smile: 

I would propose to remove the "params" field in [`Request.serialize`](https://github.com/emlove/jsonrpc-base/blob/main/jsonrpc_base/jsonrpc.py#L196-L197) not only when it's `None`, but also when it's empty (i.e. when calling a method without any parameters).

##### Motivations:

- Performance in the form of smaller messages
- For my particular use-case I have a server that does not support empty objects/dicts specifically (we have a C++ implementation without any argument-name mapping - only positional arguments work). I am currently doing a workaround by monkey-patching the implementation of serialize with:

  ```python
  original_serialize = Request.serialize
  def remove_empty_params(request: Request):
      data = json.loads(original_serialize(request))
      if 'params' in data and len(data['params']) == 0:
          del data['params']
      return json.dumps(data)
  Request.serialize = remove_empty_params
  ```

I hope that would be a worthwile addition. I would gladly submit a PR if this is deemed useful :smile:

EDIT:

Forgot to mention the actual reference that omitting "params" is actually possible according to the [JSON-RPC spec](https://www.jsonrpc.org/specification#request_object).

**Comment by emlove** [comment]
Thanks for the proposal, yeah that makes sense to me! If you're willing to put together a PR I'd be happy to merge. Please make sure to include tests!

**Comment by Makman2** [comment]
@emlove submitted :wink:
